### ISSUE TITLE
Enlace a ACP erróneo después de actualizar.

### ISSUE THREAD

**Issue by Sama34** [Anio-pke/mybb18-spanish-translation#3]
Hay un error en el paquete que muestra un enlace erróneo al terminar la actualización del foro.

mybb/mybb#2028

https://github.com/Anio-pke/mybb18-spanish-translation/blob/master/install/resources/language.lang.php#L354

https://github.com/mybb/mybb/blob/feature/install/resources/language.lang.php#L353

**Comment by Anio-pke** [comment]
Listo, solucionado. Gracias. ;)
