### ISSUE TITLE
mybb_theme_colors.xml

### ISSUE THREAD

**Issue by Diego-Pino** [Anio-pke/mybb18-spanish-translation#6]
Hola, Se deberia de actualizar el instalador en **mybb_theme_colors.xml** definiendo bien la palabra **Crepúsculo**.. quitandole la **tilde**
Tal cual lo hablamos en  
[https://community.mybb.com/thread-158393-post-1310027.html#pid1310027](https://community.mybb.com/thread-158393-post-1310027.html#pid1310027)

**Comment by Anio-pke** [comment]
Ya estaba arreglado tras mi primera respuesta: https://github.com/Anio-pke/mybb18-spanish-translation/commit/98b25180d83908f5c52df27b2f7ec69b0e2be710
